const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
  const titles = [
    { name: 'くぅー見習い', level: 1 },
    { name: '駆け出しのくぅー', level: 2 },
    { name: 'くぅーマスター', level: 3 },
    { name: 'くぅーソムリエ', level: 4 },
    { name: 'くぅーエヴァンジェリスト', level: 5 },
    { name: 'くぅー仙人', level: 6 },
    { name: 'くぅー神', level: 7 },
    { name: 'くぅーエンペラー', level: 8 },
    { name: 'リビングレジェンドくぅー', level: 9 },
    { name: 'くぅーの化身', level: 10 },
    { name: '歩くくぅー', level: 11 },
    { name: 'くぅーそのもの', level: 12 },
    { name: 'くぅー探検隊', level: 13 },
    { name: 'くぅー無限湧き', level: 14 },
    { name: 'くぅー最終形態', level: 15 },
    { name: 'くぅー・デ・オージャス', level: 16 },
    { name: 'くぅー警備隊長', level: 17 },
    { name: 'くぅー学概論教授', level: 18 },
    { name: 'くぅー is ライフ', level: 19 },
    { name: 'くぅーいただきました！', level: 20 },
    { name: 'くぅー year！', level: 21 },
    { name: 'くぅーしか勝たん', level: 22 },
    { name: 'くぅーの呼吸 壱ノ型', level: 23 },
    { name: 'くぅーに始まりくぅーに終わる', level: 24 },
    { name: 'くぅーで天下統一', level: 25 },
    { name: '自走式くぅー', level: 26 },
    { name: 'くぅー型決戦兵器', level: 27 },
    { name: 'くぅーtime', level: 28 },
    { name: 'くぅーしか信じない', level: 29 },
    { name: 'くぅーの夢を見る', level: 30 },
    { name: '今日もくぅー日和', level: 31 },
    { name: '晩餐はくぅー', level: 32 },
    { name: 'くぅーダビデ像', level: 33 },
    { name: 'くぅービッグバン', level: 34 },
    { name: 'くぅーアルティメット', level: 35 },
    { name: 'くぅー・オブ・ジョイトイ', level: 36 },
    { name: 'くぅーこそ正義', level: 37 },
    { name: 'くぅーなる秩序', level: 38 },
    { name: 'くぅーリューション', level: 39 },
    { name: 'くぅーティスト', level: 40 },
    { name: 'くぅーニング', level: 41 },
    { name: 'くぅーカイザー', level: 42 },
    { name: 'くぅー将軍', level: 43 },
    { name: 'くぅー式アロマ', level: 44 },
    { name: 'くぅーミルフィーユ', level: 45 },
    { name: 'くぅーベルク', level: 46 },
    { name: 'くぅーバリア', level: 47 },
    { name: 'くぅーインパクト', level: 48 },
    { name: 'くぅーイノベーション', level: 49 },
    { name: 'くぅーエナジー', level: 50 },
    { name: 'くぅーマニアックス', level: 51 },
    { name: 'くぅーロマンス', level: 52 },
    { name: '全知全能のくぅー', level: 53 },
    { name: 'くぅーとんきょう', level: 54 },
    { name: 'くぅーイズム', level: 55 },
    { name: 'くぅー！まかせんしゃい！', level: 56 },
    { name: 'くぅー食いねぇ！', level: 57 },
    { name: 'くぅー寝る！', level: 58 },
    { name: 'くぅー！許してヒヤシンス！', level: 59 },
    { name: 'くぅーは文化！', level: 60 },
    { name: 'くぅー！もはや意味不明！', level: 61 },
    { name: '脳内くぅー再生マシーン', level: 62 },
    { name: 'くぅー言っときゃ何とかなる', level: 63 },
    { name: 'くぅー系YouTuber', level: 64 },
    { name: 'くぅーしか喋れない', level: 65 },
    { name: 'くぅー教教祖', level: 66 },
    { name: 'くぅーに全てを捧げた男', level: 67 },
    { name: 'くぅーの申し子', level: 68 },
    { name: 'くぅーって言いたいだけ', level: 69 },
    { name: 'くぅー！ふざけんな！', level: 70 },
    { name: 'くぅー！マジ卍！', level: 71 },
    { name: 'くぅーの権化', level: 72 },
    { name: 'くぅーしか愛せない', level: 73 },
    { name: 'くぅーチャンス！', level: 74 },
    { name: 'くぅー案件ください', level: 75 },
    { name: 'くぅー！それな！', level: 76 },
    { name: 'とりあえずくぅー', level: 77 },
    { name: 'くぅー！知らんけど！', level: 78 },
    { name: 'くぅー！うるせぇ！', level: 79 },
    { name: 'くぅーは裏切らない', level: 80 },
    { name: 'くぅー！おやすみプンプン！', level: 81 },
    { name: 'くぅー！エモい！', level: 82 },
    { name: 'くぅー！優勝！', level: 83 },
    { name: 'くぅー！草！', level: 84 },
    { name: 'くぅー！尊い！', level: 85 },
    { name: 'くぅー is GOD', level: 86 },
    { name: 'くぅーしか勝たん！【公式】', level: 87 },
    { name: 'くぅーで地球を救う', level: 88 },
    { name: 'くぅーの錬金術師', level: 89 },
    { name: 'くぅーデストロイヤー', level: 90 },
    { name: 'くぅー・ザ・ワールド', level: 91 },
    { name: 'くぅー・オブ・レジェンド', level: 92 },
    { name: 'くぅーファイナリスト', level: 93 },
    { name: 'くぅーインフルエンサー', level: 94 },
    { name: 'くぅーアドバイザー', level: 95 },
    { name: 'くぅーウォッチャー', level: 96 },
    { name: 'くぅーソウル', level: 97 },
    { name: 'くぅーメサイア', level: 98 },
    { name: 'くぅー・ターミネーター', level: 99 },
    { name: 'くぅーウェーブ', level: 100 },
    { name: 'くぅーオーケストラ', level: 101 },
    { name: 'くぅーの恩返し', level: 102 },
    { name: 'くぅーの奇妙な冒険', level: 103 },
    { name: 'くぅーラプソディー', level: 104 },
    { name: 'くぅー革命', level: 105 },
    { name: 'くぅーを止めるな！', level: 106 },
    { name: 'くぅーin the Sky', level: 107 },
    { name: 'くぅーランドの王', level: 108 },
    { name: 'くぅー型AI', level: 109 },
    { name: 'くぅー過ぎる日々', level: 110 },
    { name: 'くぅーの逆襲', level: 111 },
    { name: 'くぅー脳100％', level: 112 },
    { name: 'くぅーハラスメント', level: 113 },
    { name: 'くぅーの恩寵', level: 114 },
    { name: 'くぅー・イン・ワンダーランド', level: 115 },
    { name: 'くぅーも歩けば棒に当たる', level: 116 },
    { name: 'くぅー界の希望', level: 117 },
    { name: 'くぅー数珠つなぎ', level: 118 },
    { name: 'くぅー無双', level: 119 },
    { name: 'くぅー・ザ・ファースト', level: 120 },
    { name: 'くぅー専用モビルスーツ', level: 121 },
    { name: 'くぅー将軍の休日', level: 122 },
    { name: 'くぅー警察出動', level: 123 },
    { name: 'くぅーおかわり！', level: 124 },
    { name: 'くぅーやっとる？', level: 125 },
    { name: 'くぅーのくぅーによるくぅーのためのくぅー', level: 126 },
    { name: 'くぅー2ndインパクト', level: 127 },
    { name: 'くぅー養成所卒業生', level: 128 },
    { name: 'くぅー沼の住人', level: 129 },
    { name: 'くぅーの塔を登る者', level: 130 },
    { name: 'くぅーfor President', level: 131 },
    { name: 'くぅーは突然に', level: 132 },
    { name: 'くぅー100連打チャレンジャー', level: 133 },
    { name: 'くぅーレンジャー', level: 134 },
    { name: 'くぅーinパラレルワールド', level: 135 },
    { name: 'くぅーFES開催中', level: 136 },
    { name: 'くぅー・デ・ジャブ', level: 137 },
    { name: 'くぅーを愛しすぎた者', level: 138 },
    { name: 'くぅー待ち', level: 139 },
    { name: 'くぅー認定者', level: 140 },
    { name: 'くぅー無しでは生きられない', level: 141 },
    { name: 'くぅーの申し子2号', level: 142 },
    { name: 'くぅーサミット議長', level: 143 },
    { name: 'くぅー協会認定', level: 144 },
    { name: 'くぅーに魂を売った者', level: 145 },
    { name: 'くぅー48', level: 146 },
    { name: 'くぅー@Xアカウント', level: 147 },
    { name: 'くぅーの鼓動が聞こえる', level: 148 },
    { name: 'くぅーアセンション', level: 149 },
    { name: 'くぅー超えて光になった', level: 150 },
    { name: 'くぅー原理主義者', level: 151 },
    { name: 'くぅーの概念', level: 152 },
    { name: 'くぅー定数', level: 153 },
    { name: 'くぅー時空の旅人', level: 154 },
    { name: 'くぅーを継ぐ者', level: 155 },
    { name: 'くぅーエクスプローラー', level: 156 },
    { name: 'くぅー・コード', level: 157 },
    { name: 'くぅーの楽園', level: 158 },
    { name: 'くぅーの審判者', level: 159 },
    { name: 'くぅーニバース', level: 160 },
    { name: 'くぅーの哲学者', level: 161 },
    { name: 'くぅー時間管理局', level: 162 },
    { name: 'くぅー・リベレーター', level: 163 },
    { name: 'くぅー超銀河団', level: 164 },
    { name: 'くぅー神話創世編', level: 165 },
    { name: 'くぅー伝承継承者', level: 166 },
    { name: 'くぅーの光と影', level: 167 },
    { name: 'くぅー・ゼロ', level: 168 },
    { name: 'くぅーの中心で愛を叫ぶ', level: 169 },
    { name: 'くぅー黙示録', level: 170 },
    { name: 'くぅー無限拡張パック', level: 171 },
    { name: 'くぅーAI覚醒体', level: 172 },
    { name: 'くぅー=イデア論', level: 173 },
    { name: 'くぅー方程式', level: 174 },
    { name: 'くぅー無の境地', level: 175 },
    { name: 'くぅーコード最終形', level: 176 },
    { name: 'くぅー惑星開発委員会', level: 177 },
    { name: 'くぅー宇宙漂流者', level: 178 },
    { name: 'くぅー創造神話', level: 179 },
    { name: 'くぅーの終焉', level: 180 },
    { name: 'くぅーの再誕', level: 181 },
    { name: 'くぅー新世界の神', level: 182 },
    { name: 'くぅー概念体', level: 183 },
    { name: 'くぅー世界線越境者', level: 184 },
    { name: 'くぅー完全体', level: 185 },
    { name: 'くぅー最後の継承者', level: 186 },
    { name: 'くぅーの再定義', level: 187 },
    { name: 'くぅー言語化不可能', level: 188 },
    { name: 'くぅー粒子加速器', level: 189 },
    { name: 'くぅーの終末時計', level: 190 },
    { name: 'くぅーの宇宙方舟', level: 191 },
    { name: 'くぅー超越体', level: 192 },
    { name: 'くぅーの輪廻', level: 193 },
    { name: 'くぅーin the Multiverse', level: 194 },
    { name: 'くぅー・エピローグ', level: 195 },
    { name: 'くぅーの無意識', level: 196 },
    { name: 'くぅー帰還者', level: 197 },
    { name: 'くぅー100億光年の彼方', level: 198 },
    { name: 'くぅー・ビッグリターン', level: 199 },
    { name: 'くぅー無限回廊の覇者', level: 200 },
  ];
  for (const t of titles) {
    await prisma.kuuTitle.upsert({
      where: { level: t.level },
      update: {},
      create: t,
    });
  }
  console.log('KuuTitle seed complete!');
}

main().catch(e => {
  console.error(e);
  process.exit(1);
}).finally(() => prisma.$disconnect()); 