import type { Metadata } from "next";
import Header from '@/components/Header';
import KuuMessage from '@/components/KuuMessage';
import KuuGate from '@/components/KuuGate';
import { AuthProvider } from '@/contexts/AuthContext';
import { mplus } from '@/utils/fonts';
import "./globals.css";
import '@fortawesome/fontawesome-free/css/all.min.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className={mplus.className}>
      <body
        className="antialiased font-mplus"
      >
        <AuthProvider>
          <KuuMessage />
          <KuuGate>
            <Header />
            {children}
          </KuuGate>
        </AuthProvider>
      </body>
    </html>
  );
}
